### PR TITLE
Feedback

### PR DESCRIPTION
**Pull request by jimhommes**

### CODE REVIEW

**Comment by wouterjsmit** [comment]
Thanks for the feedback. Did you not submit sprint 5 last week already? it is in `dev`.

**Comment by jimhommes** [comment]
It is the feedback for sprint 6

**Comment by wouterjsmit** [comment]
The PR contains two commits, one being the feedback from last week (8 days ago). Could you rebase against dev?

```
git fetch origin
git checkout feedback
git rebase -i origin/dev
```

**Comment by jimhommes** [comment]
Sure there is not a difference in sprint 5? It's really weird if there is
feedback in dev that did not get through the feedback branch. Otherwise Ill
rebase when I get home.

**Comment by wouterjsmit** [comment]
The whole file is being added in this commit (looking at the diff in this PR).
If you keep a branch open without rebasing/merging/updating iwth the main branch, your commits will appear as a diff to the main.

Generally you open a new branch (under the same name if so desired rather than keeping branches).

**Comment by wouterjsmit** [comment]
@jimhommes While we are waiting for this anyway. We did upload a new Architecture Design. I'm not sure you noticed? If it was unclear, should we add versioning / mention it in the releases?

Edit: furthoremore, we aren't sure what 'feedback'  on code evolution you mean, unless you mean the feedback about the Architecture Design document.

**Comment by jimhommes** [comment]
Please do, I think I did not check it out.

Met vriendelijke groet,

Jim Hommes

**Comment by wouterjsmit** [comment]
> Please do

@jimhommes  Please do what exactly? The new document is on `dev`.

**Pull request merged**
