### PR TITLE
 Fixed the edge drawing performance

### LINKED ISSUE #182: Edge drawing optimization
Investigate if it is possible to draw the edges more efficiently, or otherwise draw fewer edges.

The application zooms/scrolls very fast when the edges are not drawn. When the edges are drawn this is not always the case (especially for larger datasets), because there can be 100's of thousands of edges at the same time and currently a separate JavaFX Line object is created for each edge. This can possibly be done more efficient if something like a Canvas is used, where it is not necessary to create a new object for every drawn line.

### PR DESCRIPTION
**Pull request by FarisElghlan**
Fixes #182

The edges are now drawn in a Canvas, resulting in lower memory
usage and faster drawing speeds.
The edge width is now approximated, so this no longer is a bottleneck
The 328 graph can now be redrawn at around 60 FPS on my PC.
The lowest FPS rate I got was around 20-25.

### CODE REVIEW

**Comment by wouterjsmit** [comment]
Please rebase against `dev` since that commit is now on `dev`.

**Comment by FarisElghlan** [comment]
Fixed (I think/hope)

**Comment by wouterjsmit** [comment]
Did you try it on the 340/328 graph?

Stuff seems pretty overloaded

**Comment by wouterjsmit** [comment]
Not sure what goes wrong with the 328 data set for me. but the optimizaiton can be merged.

**Pull request merged**
