### PR TITLE
Feat/heatmap options

### LINKED ISSUE #142: Application needs heatmap/visualizaton of the drug resitance

### PR DESCRIPTION
**Pull request by FarisElghlan**
Added a second heatmap and the possibility to change the value value which is displayed in the heatmap.

Fixes #142

### CODE REVIEW

**Comment by cbilstra** [comment]
This PR contains a lot changes which are also in the other PR (#224) or am I wrong?

**Comment by FarisElghlan** [comment]
#224 was made based on this branch

**Comment by justinvdk** [comment]
Code looks good. Only thing that caught my eye is the Iterator type of `IPhylogeneticTreeNode`.
Is this to prevent confusion with `PhylogeneticTreeNode` implementing the `Iteratable` interface himself (and thus having two `iterator()` methods?)

**Comment by FarisElghlan** [comment]
You can't implement the same interface twice with different generic types. If the `IPhylogeneticTreeNode` interface would extend `Iterable<IPhylogeneticTreeNode>` then the `PhylogeneticTreeNode` implementation of the interface would have to return an iterator with the interface as generic type, thus not allowing the `PhylogeneticTreeNode` implementation to get an iterator of its child nodes with the correct generic type.

**Comment by justinvdk** [comment]
I see. Wasn't sure whether java did support this.

**Pull request merged**
