### PR TITLE
Add Group members to readme

### PR DESCRIPTION
**Pull request by wouterjsmit**
Any comments on this readme?

### CODE REVIEW

**Comment by cathmer** [comment]
Looks good!

**Comment by wouterjsmit** [comment]
I nearly forgot: the Programming Life organization asked for pictures of us, to better get to know us.  Not entirely sure if they want it in the readme though, asking them.

**Comment by wouterjsmit** [comment]
@jimhommes Anything missing right now?

**Comment by wouterjsmit** [comment]
Postponing the milestone because @jimhommes is on a holiday

**Comment by wouterjsmit** [comment]
Feedback from @thomasabeel : photos of team members wanted on deliverables, but since these are already handed in, adding them to the readme will suffice.

**Comment by wouterjsmit** [comment]
@justinvdk @cathmer @FarisElghlan If you would upload a profile picture, I can add them to the readme and merge this

**Comment by cathmer** [comment]
@Pathemeous I uploaded a profile picture to the drive.

**Comment by cathmer** [comment]
It's probably useful if you also put in the readme how to run our project.

**Comment by wouterjsmit** [comment]
Merging without pictures for now.

**Pull request merged**
