### PR TITLE
Misc/rename annotation

### PR DESCRIPTION
**Pull request by cbilstra**
Because the AnnotationReader was actually the MetaDataReader and I want to make the AnnotationReader.

### CODE REVIEW

**Comment by wouterjsmit** [comment]
could you rebase and then force push rather than first merging the old commits?

**Comment by wouterjsmit** [comment]
A few files kept their old names:
`AnnotationReaderTest.java`
`AnnotationDAO.java`
`AnnotationDAOTest.java`

Please rename these accordingly

**Comment by cbilstra** [comment]
Looks like my commits completely disappeared but the changes are there. Squashed one commit too much?

**Comment by wouterjsmit** [comment]
Yes you did. You can probably get it back by creating a new branch based on `dev`. on there, do:

```
git cherry-pick 61e1a6e
git reset @~
git add -A
git commit
```

You can specify the new commit message then.

You should always inspect the log (`git log --oneline`) to make sure that your have the right commits before you force push.

An easy way to make sure that you only ever rebase your own changes, use the following rebasing command.
`git fetch && git rebase -i origin/dev`

I am closing this PR since the history of this branch is ruined. Don't delete the branch before the cherry-pick, otherwise commit 61e1a6e will be lost.

**Pull request closed without merging**
