### PR TITLE
Refactor genome storage

### PR DESCRIPTION
**Pull request by wouterjsmit**
The genomes are now stored using integers. This saves a lot of bandwidth. See #127.

### CODE REVIEW

**Comment by FarisElghlan** [comment]
Already checked the code/new performance last week, looks good. (from ~500MB to ~120MB if I remember correctly)

**Comment by FarisElghlan** [comment]
The genomemap needs a `clear()` method to clear its content. This must be called at the start of the `parseHeader()` method. Now it is possible to load a new graph file and still keep the old genome mappings (which don't exist anymore in the graph). This causes problems when trying to parse over all genomes in the map (ex. when searching a genome by name).

**Comment by wouterjsmit** [comment]
@FarisElghlan Added.

**Comment by justinvdk** [comment]
As far as I'm concerned we can merge this PR.

**Pull request merged**
