### PR TITLE
Feat/tree graph integration

### PR DESCRIPTION
**Pull request by FarisElghlan**
Fixed all checkstyle and PMD warnings in the gui module and merged the graph into the application.

### CODE REVIEW

**Comment by wouterjsmit** [comment]
The branch has conflicts, so we cannot merge it just yet. Assuming that you are working on this offline today, this is not ready for merging.

Would love to not have so many merge commits in the PR and generally more commit message convention.
- Only imperative mood in commit title (`add`)
- Title max `50` characters long
- Don't end the title with a period `.`

**Comment by FarisElghlan** [comment]
Ok I have fixed the merge confilcts. The merge conflicts actually occured after I had made the pull request (when a different pull request was acceepted), so I didn't notice it till now.
The imperative mood just sounds really stupid to me when writing commit messages, since I commit after I have changed the code, so I really can't do that. I will keep the other 2 points in mind for next time.

**Comment by wouterjsmit** [comment]
I can live with that.

`PL2/PL2-gui/nb-configuration.xml` is added to the PR, but you also added `nb-configuration.xml` to the `.gitignore`. I'm supposing this is a mistake?

**Comment by wouterjsmit** [comment]
The code looks a lot cleaner. If you can remove the `nb-configuration.xml`, this should be ready for merging.

**Comment by FarisElghlan** [comment]
Ok fixed it.

**Pull request merged**
