### PR TITLE
Annotation bugfix and extra heatmap

### PR DESCRIPTION
**Pull request by FarisElghlan**
Fixed some small bugs before the presentation

### CODE REVIEW

**Comment by justinvdk** [comment]
I agree with those changes. Seen the bugs firsthand and think they should be included.
NOTE: also adds an extra heatmap option for the graph, which technically is a new feature. (hence the gui tag)

**Comment by wouterjsmit** [comment]
I don't want to become nazi again, but I kinda do.

Could you separate your commits to reflect the bug fixes. Also ahve a commit message that explains what was wrong (why was the change necessary and why the way you implemented it)

Otherwise I'm sure your code is correct.

**Comment by wouterjsmit** [comment]
Please do this since I want to merge your code

**Comment by wouterjsmit** [comment]
Thanks, merging

**Comment by FarisElghlan** [comment]
...

**Comment by FarisElghlan** [comment]
?

**Comment by wouterjsmit** [comment]
Sorry, waiting for checks but then had to travel.

**Pull request merged**
