### PR TITLE
Remove hardcoded background color

### PR DESCRIPTION
**Pull request by justinvdk**

### CODE REVIEW

**Comment by FarisElghlan** [comment]
No nice imports :(
(also got an unused private field)

**Comment by justinvdk** [comment]
Welp, that was stupid. Recommited.

**Comment by FarisElghlan** [comment]
Nice imports :tada:

**Comment by wouterjsmit** [comment]
Wooh! coverage!!!

I don't know what this PR is about, but it increases coverage by a whopping **0.02%**!!!

Mad skills bro!

Changes look good, merging.

**Pull request merged**
